refresh_rate: 30 seconds

appenders:
  stdout:
    kind: console
    encoder:
      pattern: "{l} - {m}{n}"

  rolling_file:
    kind: rolling_file
    path: "logs/output.log"
    encoder:
      pattern: "{d} {l} {t} - {m}{n}"
    policy:
      kind: compound
      trigger:
        kind: size
        limit: 1mb
      roller:
        kind: fixed_window
        base: 1
        count: 5
        pattern: "logs/output.{}.log"

root:
  level: info
  appenders:
    - stdout
    - rolling_file
